# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maricula', models.PositiveSmallIntegerField(unique=True)),
                ('fmatricula', models.DateTimeField(auto_now_add=True)),
                ('genero', models.SmallIntegerField(choices=[(0, 'Hombre'), (1, 'Mujer')])),
                ('apaterno', models.CharField(max_length=60)),
                ('amaterno', models.CharField(blank=True, max_length=60, null=True)),
                ('nombre', models.CharField(max_length=60)),
                ('fnacimiento', models.DateField()),
                ('grado_escolar', models.SmallIntegerField(choices=[(0, 'Primaria'), (1, 'Secundaria'), (2, 'Preparaoria'), (3, 'Profecional')])),
                ('lugar_trabajo', models.CharField(blank=True, max_length=80, null=True)),
                ('puesto_trabajo', models.CharField(blank=True, max_length=40, null=True)),
                ('domicilio', models.TextField()),
                ('cp', models.IntegerField(default=84000)),
                ('colonia', models.CharField(blank=True, max_length=80, null=True)),
                ('nombre_tutor', models.CharField(blank=True, max_length=80, null=True)),
                ('tel_celular', models.CharField(blank=True, max_length=20, null=True)),
                ('tel_casa', models.CharField(blank=True, max_length=20, null=True)),
                ('tel_trabajo', models.CharField(blank=True, max_length=20, null=True)),
                ('tel_tutor', models.CharField(blank=True, max_length=20, null=True)),
                ('email_estudiante', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_tutor1', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_tutor2', models.EmailField(blank=True, max_length=254, null=True)),
                ('curp', models.BooleanField()),
                ('acta_nacimiento', models.BooleanField()),
                ('credencial_elector', models.BooleanField()),
                ('boleta_certificado', models.BooleanField()),
                ('comprobante_dom', models.BooleanField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('reg_curp', models.CharField(max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area_Estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30)),
                ('duracion', models.CharField(max_length=20)),
                ('costo_inscripcion', models.DecimalField(decimal_places=2, max_digits=6)),
                ('costo_semanal', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=30)),
                ('dias', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='area_estudios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Area_Estudio'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Horario'),
        ),
    ]
